/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistema.GUI;
import sistema.Modelos.*;
import sistema.DAO.*;
import java.util.List;
import java.util.ArrayList;

/**
 *
 * @author Ju
 */
public class Adm extends javax.swing.JFrame {
    UsuariosTableModel usuariosTable = new UsuariosTableModel();
    ProdutosTableModel produtosTable = new ProdutosTableModel();
    
    boolean recebidosControle = true;
    RecebidosTableModel recebidosTable = new RecebidosTableModel();
    ProdutosTableModel novoRecebidosTable = new ProdutosTableModel();
    
    boolean vendasControle = true;
    VendasTableModel vendasTable = new VendasTableModel();
    ProdutosTableModel novoVendasTable = new ProdutosTableModel();
    
    public Adm() {
        initComponents();
        setLocationRelativeTo(null);
        pnlMenuInicial.setVisible(true);
        pnlUsuarios.setVisible(false);
        pnlProdutos.setVisible(false);
        pnlRecebimentos.setVisible(false);
        pnlVendas.setVisible(false);
                
        tblUsuarios.setModel(usuariosTable);
        tblUsuarios.setAutoCreateRowSorter(true);
        
        tblProdutos.setModel(produtosTable);
        tblProdutos.setAutoCreateRowSorter(true);
                        
        tblRecebimentos.setAutoCreateRowSorter(true);
        btnRecebimentosRemover.setVisible(false);
        btnRecebimentosEditar.setVisible(false);
        btnRecebimentosNovo.setVisible(false);
        
        tblVendas.setAutoCreateRowSorter(true);
        btnVendasRemover.setVisible(false);
        btnVendasEditar.setVisible(false);
        btnVendasNovo.setVisible(false);
            
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenuInicial = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnUsuarios = new javax.swing.JButton();
        btnProdutos = new javax.swing.JButton();
        btnRelatorios = new javax.swing.JButton();
        btnVendas = new javax.swing.JButton();
        btnRecebidos = new javax.swing.JButton();
        btnDesconectar = new javax.swing.JButton();
        pnlUsuarios = new javax.swing.JPanel();
        pnlUsuariosMenu = new javax.swing.JPanel();
        btnUsuariosVoltarMenu = new javax.swing.JButton();
        lblUsuariosPesquisa = new javax.swing.JLabel();
        txtUsuariosPesquisa = new javax.swing.JTextField();
        btnUsuariosPesquisa = new javax.swing.JButton();
        lblUsuariosExibir = new javax.swing.JLabel();
        btnUsuariosExibirTodos = new javax.swing.JButton();
        btnUsuariosExibirAdm = new javax.swing.JButton();
        btnUsuariosExibirFuncionarios = new javax.swing.JButton();
        btnUsuariosNovo = new javax.swing.JButton();
        btnUsuariosEditar = new javax.swing.JButton();
        btnUsuariosRemover = new javax.swing.JButton();
        lblTituloUsuarios = new javax.swing.JLabel();
        jspUsuario = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        pnlProdutos = new javax.swing.JPanel();
        pnlProdutosMenu = new javax.swing.JPanel();
        btnProdutosVoltarMenu = new javax.swing.JButton();
        lblProdutosPesquisa = new javax.swing.JLabel();
        txtProdutosPesquisa = new javax.swing.JTextField();
        btnProdutosPesquisa = new javax.swing.JButton();
        lblProdutosExibirAlfabetica = new javax.swing.JLabel();
        btnProdutosNovo = new javax.swing.JButton();
        btnProdutosEditar = new javax.swing.JButton();
        btnProdutosRemover = new javax.swing.JButton();
        btnProdutosExibirTodos = new javax.swing.JButton();
        btnProdutosExibirSemEstoque = new javax.swing.JButton();
        btnProdutosExibirComEstoque = new javax.swing.JButton();
        jspProdutos = new javax.swing.JScrollPane();
        tblProdutos = new javax.swing.JTable();
        lblProdutos = new javax.swing.JLabel();
        pnlRecebimentos = new javax.swing.JPanel();
        pnlRecebimentoMenu = new javax.swing.JPanel();
        btnRecebimentosVoltarMenu = new javax.swing.JButton();
        lblRecebimentosPesquisa = new javax.swing.JLabel();
        txtRecebimentosPesquisa = new javax.swing.JTextField();
        btnRecebimentosPesquisa = new javax.swing.JButton();
        lblRecebimentosExibir = new javax.swing.JLabel();
        btnRecebimentosNovo = new javax.swing.JButton();
        btnRecebimentosEditar = new javax.swing.JButton();
        btnRecebimentosRemover = new javax.swing.JButton();
        btnRecebimentosHistorico = new javax.swing.JButton();
        btnRecebimentosRealizar = new javax.swing.JButton();
        jspRecebimentos = new javax.swing.JScrollPane();
        tblRecebimentos = new javax.swing.JTable();
        lblRecebimentos = new javax.swing.JLabel();
        pnlVendas = new javax.swing.JPanel();
        pnlVendasMenu = new javax.swing.JPanel();
        btnVendasVoltarMenu = new javax.swing.JButton();
        lblVendasPesquisa = new javax.swing.JLabel();
        txtVendasPesquisa = new javax.swing.JTextField();
        btnVendasPesquisa = new javax.swing.JButton();
        lblVendasExibir = new javax.swing.JLabel();
        btnVendasNovo = new javax.swing.JButton();
        btnVendasEditar = new javax.swing.JButton();
        btnVendasRemover = new javax.swing.JButton();
        btnVendasHistorico = new javax.swing.JButton();
        btnVendasRealizar = new javax.swing.JButton();
        jspVendas = new javax.swing.JScrollPane();
        tblVendas = new javax.swing.JTable();
        lblVendas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblTitulo.setText("Menu");

        btnUsuarios.setText("Gerenciar Usuarios");
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });

        btnProdutos.setText("Gerenciar Produtos");
        btnProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutosActionPerformed(evt);
            }
        });

        btnRelatorios.setText("Exibir Relatorios");
        btnRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatoriosActionPerformed(evt);
            }
        });

        btnVendas.setText("Gerenciar Venda");
        btnVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendasActionPerformed(evt);
            }
        });

        btnRecebidos.setText("Gerenciar Recebimentos");
        btnRecebidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecebidosActionPerformed(evt);
            }
        });

        btnDesconectar.setText("Desconectar");
        btnDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesconectarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuInicialLayout = new javax.swing.GroupLayout(pnlMenuInicial);
        pnlMenuInicial.setLayout(pnlMenuInicialLayout);
        pnlMenuInicialLayout.setHorizontalGroup(
            pnlMenuInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuInicialLayout.createSequentialGroup()
                .addGap(352, 352, 352)
                .addComponent(btnDesconectar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuInicialLayout.createSequentialGroup()
                .addContainerGap(250, Short.MAX_VALUE)
                .addGroup(pnlMenuInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuInicialLayout.createSequentialGroup()
                        .addGroup(pnlMenuInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnRecebidos, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRelatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(250, 250, 250))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuInicialLayout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addGap(350, 350, 350))))
        );
        pnlMenuInicialLayout.setVerticalGroup(
            pnlMenuInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuInicialLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblTitulo)
                .addGap(64, 64, 64)
                .addComponent(btnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRelatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRecebidos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnDesconectar)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pnlUsuarios.setPreferredSize(new java.awt.Dimension(800, 600));

        pnlUsuariosMenu.setBackground(new java.awt.Color(220, 220, 220));

        btnUsuariosVoltarMenu.setText("< Voltar");
        btnUsuariosVoltarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosVoltarMenuActionPerformed(evt);
            }
        });

        lblUsuariosPesquisa.setText("Pesquisa");

        btnUsuariosPesquisa.setText("Pesquisar");
        btnUsuariosPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosPesquisaActionPerformed(evt);
            }
        });

        lblUsuariosExibir.setText("Exibir:");

        btnUsuariosExibirTodos.setText("Todos");
        btnUsuariosExibirTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosExibirTodosActionPerformed(evt);
            }
        });

        btnUsuariosExibirAdm.setText("Somente Administradores");
        btnUsuariosExibirAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosExibirAdmActionPerformed(evt);
            }
        });

        btnUsuariosExibirFuncionarios.setText("Somente Funcionarios");
        btnUsuariosExibirFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosExibirFuncionariosActionPerformed(evt);
            }
        });

        btnUsuariosNovo.setText("Novo Usuario");
        btnUsuariosNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosNovoActionPerformed(evt);
            }
        });

        btnUsuariosEditar.setText("Editar");
        btnUsuariosEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosEditarActionPerformed(evt);
            }
        });

        btnUsuariosRemover.setText("Remover");
        btnUsuariosRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlUsuariosMenuLayout = new javax.swing.GroupLayout(pnlUsuariosMenu);
        pnlUsuariosMenu.setLayout(pnlUsuariosMenuLayout);
        pnlUsuariosMenuLayout.setHorizontalGroup(
            pnlUsuariosMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUsuariosMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUsuariosMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUsuariosEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUsuariosExibirAdm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUsuariosNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUsuariosExibirFuncionarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUsuariosExibirTodos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlUsuariosMenuLayout.createSequentialGroup()
                        .addGroup(pnlUsuariosMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUsuariosVoltarMenu)
                            .addComponent(lblUsuariosPesquisa)
                            .addGroup(pnlUsuariosMenuLayout.createSequentialGroup()
                                .addComponent(txtUsuariosPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUsuariosPesquisa))
                            .addComponent(lblUsuariosExibir))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnUsuariosRemover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlUsuariosMenuLayout.setVerticalGroup(
            pnlUsuariosMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUsuariosMenuLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnUsuariosVoltarMenu)
                .addGap(18, 18, 18)
                .addComponent(lblUsuariosPesquisa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlUsuariosMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuariosPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUsuariosPesquisa))
                .addGap(30, 30, 30)
                .addComponent(lblUsuariosExibir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUsuariosExibirTodos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUsuariosExibirAdm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUsuariosExibirFuncionarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUsuariosRemover)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUsuariosEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUsuariosNovo)
                .addGap(77, 77, 77))
        );

        lblTituloUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTituloUsuarios.setText("Usuarios");

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jspUsuario.setViewportView(tblUsuarios);

        javax.swing.GroupLayout pnlUsuariosLayout = new javax.swing.GroupLayout(pnlUsuarios);
        pnlUsuarios.setLayout(pnlUsuariosLayout);
        pnlUsuariosLayout.setHorizontalGroup(
            pnlUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlUsuariosMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUsuariosLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jspUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlUsuariosLayout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(lblTituloUsuarios)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        pnlUsuariosLayout.setVerticalGroup(
            pnlUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUsuariosLayout.createSequentialGroup()
                        .addComponent(lblTituloUsuarios)
                        .addGap(18, 18, 18)
                        .addComponent(jspUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE))
                    .addComponent(pnlUsuariosMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlProdutos.setPreferredSize(new java.awt.Dimension(800, 600));

        pnlProdutosMenu.setBackground(new java.awt.Color(220, 220, 220));

        btnProdutosVoltarMenu.setText("< Voltar");
        btnProdutosVoltarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutosVoltarMenuActionPerformed(evt);
            }
        });

        lblProdutosPesquisa.setText("Pesquisa");

        btnProdutosPesquisa.setText("Pesquisar");
        btnProdutosPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutosPesquisaActionPerformed(evt);
            }
        });

        lblProdutosExibirAlfabetica.setText("Exibir:");

        btnProdutosNovo.setText("Novo Produto");
        btnProdutosNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutosNovoActionPerformed(evt);
            }
        });

        btnProdutosEditar.setText("Editar");
        btnProdutosEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutosEditarActionPerformed(evt);
            }
        });

        btnProdutosRemover.setText("Remover");
        btnProdutosRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutosRemoverActionPerformed(evt);
            }
        });

        btnProdutosExibirTodos.setText("Todos");
        btnProdutosExibirTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutosExibirTodosActionPerformed(evt);
            }
        });

        btnProdutosExibirSemEstoque.setText("Sem Estoque");
        btnProdutosExibirSemEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutosExibirSemEstoqueActionPerformed(evt);
            }
        });

        btnProdutosExibirComEstoque.setText("Com Estoque");
        btnProdutosExibirComEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutosExibirComEstoqueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlProdutosMenuLayout = new javax.swing.GroupLayout(pnlProdutosMenu);
        pnlProdutosMenu.setLayout(pnlProdutosMenuLayout);
        pnlProdutosMenuLayout.setHorizontalGroup(
            pnlProdutosMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProdutosMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlProdutosMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnProdutosExibirTodos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProdutosEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProdutosNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProdutosRemover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProdutosExibirSemEstoque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlProdutosMenuLayout.createSequentialGroup()
                        .addGroup(pnlProdutosMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnProdutosVoltarMenu)
                            .addComponent(lblProdutosPesquisa)
                            .addGroup(pnlProdutosMenuLayout.createSequentialGroup()
                                .addComponent(txtProdutosPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnProdutosPesquisa))
                            .addComponent(lblProdutosExibirAlfabetica))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnProdutosExibirComEstoque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlProdutosMenuLayout.setVerticalGroup(
            pnlProdutosMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProdutosMenuLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnProdutosVoltarMenu)
                .addGap(18, 18, 18)
                .addComponent(lblProdutosPesquisa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlProdutosMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProdutosPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProdutosPesquisa))
                .addGap(30, 30, 30)
                .addComponent(lblProdutosExibirAlfabetica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProdutosExibirTodos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProdutosExibirSemEstoque)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProdutosExibirComEstoque)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnProdutosRemover)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProdutosEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProdutosNovo)
                .addGap(77, 77, 77))
        );

        tblProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jspProdutos.setViewportView(tblProdutos);

        lblProdutos.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblProdutos.setText("Produtos");

        javax.swing.GroupLayout pnlProdutosLayout = new javax.swing.GroupLayout(pnlProdutos);
        pnlProdutos.setLayout(pnlProdutosLayout);
        pnlProdutosLayout.setHorizontalGroup(
            pnlProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlProdutosMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProdutosLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jspProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlProdutosLayout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(lblProdutos)))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        pnlProdutosLayout.setVerticalGroup(
            pnlProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProdutosLayout.createSequentialGroup()
                .addGroup(pnlProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProdutosLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblProdutos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jspProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProdutosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlProdutosMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pnlRecebimentos.setPreferredSize(new java.awt.Dimension(800, 600));

        pnlRecebimentoMenu.setBackground(new java.awt.Color(220, 220, 220));

        btnRecebimentosVoltarMenu.setText("< Voltar");
        btnRecebimentosVoltarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecebimentosVoltarMenuActionPerformed(evt);
            }
        });

        lblRecebimentosPesquisa.setText("Pesquisa");

        btnRecebimentosPesquisa.setText("Pesquisar");
        btnRecebimentosPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecebimentosPesquisaActionPerformed(evt);
            }
        });

        lblRecebimentosExibir.setText("Exibir:");

        btnRecebimentosNovo.setText("Novo Recebimento");
        btnRecebimentosNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecebimentosNovoActionPerformed(evt);
            }
        });

        btnRecebimentosEditar.setText("Editar");
        btnRecebimentosEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecebimentosEditarActionPerformed(evt);
            }
        });

        btnRecebimentosRemover.setText("Remover");
        btnRecebimentosRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecebimentosRemoverActionPerformed(evt);
            }
        });

        btnRecebimentosHistorico.setText("Historico de Recebimentos");
        btnRecebimentosHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecebimentosHistoricoActionPerformed(evt);
            }
        });

        btnRecebimentosRealizar.setText("Realizar Recebimento");
        btnRecebimentosRealizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecebimentosRealizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRecebimentoMenuLayout = new javax.swing.GroupLayout(pnlRecebimentoMenu);
        pnlRecebimentoMenu.setLayout(pnlRecebimentoMenuLayout);
        pnlRecebimentoMenuLayout.setHorizontalGroup(
            pnlRecebimentoMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRecebimentoMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRecebimentoMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRecebimentosHistorico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRecebimentosEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRecebimentosNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRecebimentosRemover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRecebimentosRealizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlRecebimentoMenuLayout.createSequentialGroup()
                        .addGroup(pnlRecebimentoMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRecebimentosVoltarMenu)
                            .addComponent(lblRecebimentosPesquisa)
                            .addGroup(pnlRecebimentoMenuLayout.createSequentialGroup()
                                .addComponent(txtRecebimentosPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRecebimentosPesquisa))
                            .addComponent(lblRecebimentosExibir))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlRecebimentoMenuLayout.setVerticalGroup(
            pnlRecebimentoMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRecebimentoMenuLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnRecebimentosVoltarMenu)
                .addGap(18, 18, 18)
                .addComponent(lblRecebimentosPesquisa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRecebimentoMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRecebimentosPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRecebimentosPesquisa))
                .addGap(30, 30, 30)
                .addComponent(lblRecebimentosExibir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRecebimentosHistorico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRecebimentosRealizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRecebimentosRemover)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRecebimentosEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRecebimentosNovo)
                .addGap(77, 77, 77))
        );

        tblRecebimentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jspRecebimentos.setViewportView(tblRecebimentos);

        lblRecebimentos.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblRecebimentos.setText("Recebimentos");

        javax.swing.GroupLayout pnlRecebimentosLayout = new javax.swing.GroupLayout(pnlRecebimentos);
        pnlRecebimentos.setLayout(pnlRecebimentosLayout);
        pnlRecebimentosLayout.setHorizontalGroup(
            pnlRecebimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRecebimentosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlRecebimentoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlRecebimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRecebimentosLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jspRecebimentos, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlRecebimentosLayout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(lblRecebimentos)))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        pnlRecebimentosLayout.setVerticalGroup(
            pnlRecebimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRecebimentosLayout.createSequentialGroup()
                .addGroup(pnlRecebimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRecebimentosLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblRecebimentos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jspRecebimentos, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRecebimentosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlRecebimentoMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pnlVendas.setPreferredSize(new java.awt.Dimension(800, 600));

        pnlVendasMenu.setBackground(new java.awt.Color(220, 220, 220));

        btnVendasVoltarMenu.setText("< Voltar");
        btnVendasVoltarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendasVoltarMenuActionPerformed(evt);
            }
        });

        lblVendasPesquisa.setText("Pesquisa");

        btnVendasPesquisa.setText("Pesquisar");
        btnVendasPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendasPesquisaActionPerformed(evt);
            }
        });

        lblVendasExibir.setText("Exibir:");

        btnVendasNovo.setText("Nova Venda");
        btnVendasNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendasNovoActionPerformed(evt);
            }
        });

        btnVendasEditar.setText("Editar");
        btnVendasEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendasEditarActionPerformed(evt);
            }
        });

        btnVendasRemover.setText("Remover");
        btnVendasRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendasRemoverActionPerformed(evt);
            }
        });

        btnVendasHistorico.setText("Historico de Vendas");
        btnVendasHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendasHistoricoActionPerformed(evt);
            }
        });

        btnVendasRealizar.setText("Realizar Venda");
        btnVendasRealizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendasRealizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlVendasMenuLayout = new javax.swing.GroupLayout(pnlVendasMenu);
        pnlVendasMenu.setLayout(pnlVendasMenuLayout);
        pnlVendasMenuLayout.setHorizontalGroup(
            pnlVendasMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVendasMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlVendasMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVendasHistorico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVendasEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVendasNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVendasRemover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVendasRealizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlVendasMenuLayout.createSequentialGroup()
                        .addGroup(pnlVendasMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVendasVoltarMenu)
                            .addComponent(lblVendasPesquisa)
                            .addGroup(pnlVendasMenuLayout.createSequentialGroup()
                                .addComponent(txtVendasPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnVendasPesquisa))
                            .addComponent(lblVendasExibir))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlVendasMenuLayout.setVerticalGroup(
            pnlVendasMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVendasMenuLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnVendasVoltarMenu)
                .addGap(18, 18, 18)
                .addComponent(lblVendasPesquisa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlVendasMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVendasPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVendasPesquisa))
                .addGap(30, 30, 30)
                .addComponent(lblVendasExibir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVendasHistorico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVendasRealizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVendasRemover)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVendasEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVendasNovo)
                .addGap(77, 77, 77))
        );

        tblVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jspVendas.setViewportView(tblVendas);

        lblVendas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblVendas.setText("Vendas");

        javax.swing.GroupLayout pnlVendasLayout = new javax.swing.GroupLayout(pnlVendas);
        pnlVendas.setLayout(pnlVendasLayout);
        pnlVendasLayout.setHorizontalGroup(
            pnlVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVendasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlVendasMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlVendasLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jspVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(7, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVendasLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblVendas)
                        .addGap(235, 235, 235))))
        );
        pnlVendasLayout.setVerticalGroup(
            pnlVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVendasLayout.createSequentialGroup()
                .addGroup(pnlVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVendasLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblVendas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jspVendas, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVendasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlVendasMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMenuInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlProdutos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 824, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlRecebimentos, javax.swing.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlVendas, javax.swing.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMenuInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(pnlProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 12, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlRecebimentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatoriosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRelatoriosActionPerformed

    private void btnDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesconectarActionPerformed
        this.dispose();
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_btnDesconectarActionPerformed

    private void btnUsuariosVoltarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosVoltarMenuActionPerformed
        pnlMenuInicial.setVisible(true);
        pnlUsuarios.setVisible(false);        
    }//GEN-LAST:event_btnUsuariosVoltarMenuActionPerformed

    private void btnUsuariosNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosNovoActionPerformed
        UsuarioGUI novo = new UsuarioGUI();
        novo.setVisible(true);
        
    }//GEN-LAST:event_btnUsuariosNovoActionPerformed

    private void btnUsuariosExibirAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosExibirAdmActionPerformed
        UsuarioDAO exibir = new UsuarioDAO();
        exibir.conectar();
        byte cargo = 1;
        List<Usuario> administradores = exibir.listarCargo(cargo);
        usuariosTable.setTable(administradores);
        usuariosTable.fireTableDataChanged();
        exibir.desconectar();
    }//GEN-LAST:event_btnUsuariosExibirAdmActionPerformed

    private void btnUsuariosExibirFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosExibirFuncionariosActionPerformed
        UsuarioDAO exibir = new UsuarioDAO();
        exibir.conectar();
        byte cargo = 0;
        List<Usuario> funcionarios = exibir.listarCargo(cargo);
        usuariosTable.setTable(funcionarios);
        usuariosTable.fireTableDataChanged();
        exibir.desconectar();
    }//GEN-LAST:event_btnUsuariosExibirFuncionariosActionPerformed

    private void btnUsuariosExibirTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosExibirTodosActionPerformed
        UsuarioDAO exibir = new UsuarioDAO();
        exibir.conectar();
        List<Usuario> usuarios = exibir.listar();
        usuariosTable.setTable(usuarios);
        usuariosTable.fireTableDataChanged();
        exibir.desconectar();
    }//GEN-LAST:event_btnUsuariosExibirTodosActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        pnlMenuInicial.setVisible(false);
        pnlUsuarios.setVisible(true);
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnUsuariosPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosPesquisaActionPerformed
        UsuarioDAO buscar = new UsuarioDAO();
        buscar.conectar();
        List<Usuario> busca = buscar.listarPesquisa(txtUsuariosPesquisa.getText());
        usuariosTable.setTable(busca);
        usuariosTable.fireTableDataChanged();
        buscar.desconectar();
    }//GEN-LAST:event_btnUsuariosPesquisaActionPerformed

    private void btnUsuariosRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosRemoverActionPerformed
        if(tblUsuarios.getSelectedRow() != -1){
            Usuario removido = usuariosTable.remover(tblUsuarios.getSelectedRow());
            UsuarioDAO remover = new UsuarioDAO();
            remover.conectar();
            remover.remover(removido.getUsuario());
            remover.desconectar();
        }
    }//GEN-LAST:event_btnUsuariosRemoverActionPerformed

    private void btnUsuariosEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosEditarActionPerformed
        if(tblUsuarios.getSelectedRow() != -1){
            Usuario editado = usuariosTable.editar(tblUsuarios.getSelectedRow());
            UsuarioGUI editar = new UsuarioGUI(editado);
            editar.setVisible(true);
        }
    }//GEN-LAST:event_btnUsuariosEditarActionPerformed

    private void btnProdutosVoltarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutosVoltarMenuActionPerformed
        pnlMenuInicial.setVisible(true);
        pnlProdutos.setVisible(false);
    }//GEN-LAST:event_btnProdutosVoltarMenuActionPerformed

    private void btnProdutosPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutosPesquisaActionPerformed
        ProdutoDAO buscar = new ProdutoDAO();
        buscar.conectar();
        List<Produto> busca = buscar.listarPesquisa(txtProdutosPesquisa.getText());
        produtosTable.setTable(busca);
        produtosTable.fireTableDataChanged();
        buscar.desconectar();
    }//GEN-LAST:event_btnProdutosPesquisaActionPerformed

    private void btnProdutosNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutosNovoActionPerformed
        ProdutoGUI novo = new ProdutoGUI();
        novo.setVisible(true);
    }//GEN-LAST:event_btnProdutosNovoActionPerformed

    private void btnProdutosEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutosEditarActionPerformed
        if(tblProdutos.getSelectedRow() != -1){
            Produto editado = produtosTable.editar(tblProdutos.getSelectedRow());
            ProdutoGUI editar = new ProdutoGUI(editado);
            editar.setVisible(true);
        }
    }//GEN-LAST:event_btnProdutosEditarActionPerformed

    private void btnProdutosRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutosRemoverActionPerformed
        if(tblProdutos.getSelectedRow() != -1){
            Produto removido = produtosTable.remover(tblProdutos.getSelectedRow());
            ProdutoDAO remover = new ProdutoDAO();
            remover.conectar();
            remover.remover(removido.getIdProduto());
            remover.desconectar();
        }
    }//GEN-LAST:event_btnProdutosRemoverActionPerformed

    private void btnProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutosActionPerformed
        pnlMenuInicial.setVisible(false);
        pnlProdutos.setVisible(true);
    }//GEN-LAST:event_btnProdutosActionPerformed

    private void btnProdutosExibirTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutosExibirTodosActionPerformed
        ProdutoDAO exibir = new ProdutoDAO();
        exibir.conectar();
        List<Produto> produtos = exibir.listar();
        produtosTable.setTable(produtos);
        produtosTable.fireTableDataChanged();
        exibir.desconectar();
    }//GEN-LAST:event_btnProdutosExibirTodosActionPerformed

    private void btnProdutosExibirSemEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutosExibirSemEstoqueActionPerformed
        ProdutoDAO exibir = new ProdutoDAO();
        exibir.conectar();
        List<Produto> produtos = exibir.listarEstoque(false);
        produtosTable.setTable(produtos);
        produtosTable.fireTableDataChanged();
        exibir.desconectar();
    }//GEN-LAST:event_btnProdutosExibirSemEstoqueActionPerformed

    private void btnProdutosExibirComEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutosExibirComEstoqueActionPerformed
        ProdutoDAO exibir = new ProdutoDAO();
        exibir.conectar();
        List<Produto> produtos = exibir.listarEstoque(true);
        produtosTable.setTable(produtos);
        produtosTable.fireTableDataChanged();
        exibir.desconectar();
    }//GEN-LAST:event_btnProdutosExibirComEstoqueActionPerformed

    private void btnRecebimentosVoltarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecebimentosVoltarMenuActionPerformed
        pnlMenuInicial.setVisible(true);
        pnlRecebimentos.setVisible(false);
    }//GEN-LAST:event_btnRecebimentosVoltarMenuActionPerformed

    private void btnRecebimentosPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecebimentosPesquisaActionPerformed
        if(recebidosControle){
            //historico - recebidos
            RecebidoDAO buscar = new RecebidoDAO();
            buscar.conectar();
            recebidosTable.setTable(buscar.listarPesquisa(txtRecebimentosPesquisa.getText()));
            recebidosTable.fireTableDataChanged();
            buscar.desconectar();
        }
        else{
            //novo - produtos
            ProdutoDAO busca = new ProdutoDAO();
            busca.conectar();
            novoRecebidosTable.setTable(busca.listarPesquisa(txtRecebimentosPesquisa.getText()));
            novoRecebidosTable.fireTableDataChanged();
            busca.desconectar();
        }
    }//GEN-LAST:event_btnRecebimentosPesquisaActionPerformed

    private void btnRecebimentosNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecebimentosNovoActionPerformed
        if(tblRecebimentos.getSelectedRow() != -1){
            Produto recebido = novoRecebidosTable.editar(tblRecebimentos.getSelectedRow());
            RecebidoGUI novo = new RecebidoGUI(recebido);
            novo.setVisible(true);
        }
    }//GEN-LAST:event_btnRecebimentosNovoActionPerformed

    private void btnRecebimentosEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecebimentosEditarActionPerformed
        if(tblRecebimentos.getSelectedRow() != -1){
            Recebido editado = recebidosTable.editar(tblRecebimentos.getSelectedRow());
            RecebidoGUI editar = new RecebidoGUI(editado);
            editar.setVisible(true);
        }
    }//GEN-LAST:event_btnRecebimentosEditarActionPerformed

    private void btnRecebimentosRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecebimentosRemoverActionPerformed
        if(tblRecebimentos.getSelectedRow() != -1){
            Recebido removido = recebidosTable.remover(tblRecebimentos.getSelectedRow());
            RecebidoDAO remover = new RecebidoDAO();
            remover.conectar();
            remover.remover(removido.getIdRecebimento(),removido.getQtdRecebida(),removido.getProduto());
            remover.desconectar();
        }
    }//GEN-LAST:event_btnRecebimentosRemoverActionPerformed

    private void btnRecebimentosHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecebimentosHistoricoActionPerformed
        tblRecebimentos.setModel(recebidosTable);
        btnRecebimentosRemover.setVisible(true);
        btnRecebimentosEditar.setVisible(true);
        btnRecebimentosNovo.setVisible(false);
        recebidosControle = true;
        
        RecebidoDAO recebidos = new RecebidoDAO();
        recebidos.conectar();
        recebidosTable.setTable(recebidos.listar());
        recebidosTable.fireTableDataChanged();
        recebidos.desconectar();
    }//GEN-LAST:event_btnRecebimentosHistoricoActionPerformed

    private void btnRecebimentosRealizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecebimentosRealizarActionPerformed
        tblRecebimentos.setModel(novoRecebidosTable);
        btnRecebimentosRemover.setVisible(false);
        btnRecebimentosEditar.setVisible(false);
        btnRecebimentosNovo.setVisible(true);
        recebidosControle = false;
        
        ProdutoDAO novoRecebimento = new ProdutoDAO();
        novoRecebimento.conectar();
        novoRecebidosTable.setTable(novoRecebimento.listar());
        novoRecebidosTable.fireTableDataChanged();
        novoRecebimento.desconectar();
    }//GEN-LAST:event_btnRecebimentosRealizarActionPerformed

    private void btnRecebidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecebidosActionPerformed
        pnlMenuInicial.setVisible(false);
        pnlRecebimentos.setVisible(true);
    }//GEN-LAST:event_btnRecebidosActionPerformed

    private void btnVendasVoltarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendasVoltarMenuActionPerformed
        pnlMenuInicial.setVisible(true);
        pnlVendas.setVisible(false);
    }//GEN-LAST:event_btnVendasVoltarMenuActionPerformed

    private void btnVendasPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendasPesquisaActionPerformed
        if(vendasControle){
            //historico - vendas
            VendaDAO buscar = new VendaDAO();
            buscar.conectar();
            vendasTable.setTable(buscar.listarPesquisa(txtVendasPesquisa.getText()));
            vendasTable.fireTableDataChanged();
            buscar.desconectar();
        }
        else{
            //novo - produtos
            ProdutoDAO buscar = new ProdutoDAO();
            buscar.conectar();
            novoVendasTable.setTable(buscar.listarPesquisa(txtVendasPesquisa.getText()));
            novoVendasTable.fireTableDataChanged();
            buscar.desconectar();
        }
    }//GEN-LAST:event_btnVendasPesquisaActionPerformed

    private void btnVendasNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendasNovoActionPerformed
        if(tblVendas.getSelectedRow() != -1){
            Produto recebido = novoVendasTable.editar(tblVendas.getSelectedRow());
            VendaGUI novo = new VendaGUI(recebido);
            novo.setVisible(true);
        }
    }//GEN-LAST:event_btnVendasNovoActionPerformed

    private void btnVendasEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendasEditarActionPerformed
        if(tblVendas.getSelectedRow() != -1){
            Venda editado = vendasTable.editar(tblVendas.getSelectedRow());
            VendaGUI editar = new VendaGUI(editado);
            editar.setVisible(true);
        }
    }//GEN-LAST:event_btnVendasEditarActionPerformed

    private void btnVendasRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendasRemoverActionPerformed
        if(tblVendas.getSelectedRow() != -1){
            Venda removido = vendasTable.remover(tblVendas.getSelectedRow());
            VendaDAO remover = new VendaDAO();
            remover.conectar();
            remover.remover(removido.getIdVenda(),removido.getQtdVendida(),removido.getProduto());
            remover.desconectar();
        }
    }//GEN-LAST:event_btnVendasRemoverActionPerformed

    private void btnVendasHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendasHistoricoActionPerformed
        tblVendas.setModel(vendasTable);
        btnVendasRemover.setVisible(true);
        btnVendasEditar.setVisible(true);
        btnVendasNovo.setVisible(false);
        vendasControle = true;
        
        VendaDAO vendas = new VendaDAO();
        vendas.conectar();
        vendasTable.setTable(vendas.listar());
        vendasTable.fireTableDataChanged();
        vendas.desconectar();
    }//GEN-LAST:event_btnVendasHistoricoActionPerformed

    private void btnVendasRealizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendasRealizarActionPerformed
        tblVendas.setModel(novoVendasTable);
        btnVendasRemover.setVisible(false);
        btnVendasEditar.setVisible(false);
        btnVendasNovo.setVisible(true);
        vendasControle = false;
        
        ProdutoDAO novaVenda = new ProdutoDAO();
        novaVenda.conectar();
        novoVendasTable.setTable(novaVenda.listar());
        novoVendasTable.fireTableDataChanged();
        novaVenda.desconectar();
    }//GEN-LAST:event_btnVendasRealizarActionPerformed

    private void btnVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendasActionPerformed
        pnlMenuInicial.setVisible(false);
        pnlVendas.setVisible(true);
    }//GEN-LAST:event_btnVendasActionPerformed

    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
       
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //Create and display the form
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Adm().setVisible(true);
            }
        });
    }

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDesconectar;
    private javax.swing.JButton btnProdutos;
    private javax.swing.JButton btnProdutosEditar;
    private javax.swing.JButton btnProdutosExibirComEstoque;
    private javax.swing.JButton btnProdutosExibirSemEstoque;
    private javax.swing.JButton btnProdutosExibirTodos;
    private javax.swing.JButton btnProdutosNovo;
    private javax.swing.JButton btnProdutosPesquisa;
    private javax.swing.JButton btnProdutosRemover;
    private javax.swing.JButton btnProdutosVoltarMenu;
    private javax.swing.JButton btnRecebidos;
    private javax.swing.JButton btnRecebimentosEditar;
    private javax.swing.JButton btnRecebimentosHistorico;
    private javax.swing.JButton btnRecebimentosNovo;
    private javax.swing.JButton btnRecebimentosPesquisa;
    private javax.swing.JButton btnRecebimentosRealizar;
    private javax.swing.JButton btnRecebimentosRemover;
    private javax.swing.JButton btnRecebimentosVoltarMenu;
    private javax.swing.JButton btnRelatorios;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JButton btnUsuariosEditar;
    private javax.swing.JButton btnUsuariosExibirAdm;
    private javax.swing.JButton btnUsuariosExibirFuncionarios;
    private javax.swing.JButton btnUsuariosExibirTodos;
    private javax.swing.JButton btnUsuariosNovo;
    private javax.swing.JButton btnUsuariosPesquisa;
    private javax.swing.JButton btnUsuariosRemover;
    private javax.swing.JButton btnUsuariosVoltarMenu;
    private javax.swing.JButton btnVendas;
    private javax.swing.JButton btnVendasEditar;
    private javax.swing.JButton btnVendasHistorico;
    private javax.swing.JButton btnVendasNovo;
    private javax.swing.JButton btnVendasPesquisa;
    private javax.swing.JButton btnVendasRealizar;
    private javax.swing.JButton btnVendasRemover;
    private javax.swing.JButton btnVendasVoltarMenu;
    private javax.swing.JScrollPane jspProdutos;
    private javax.swing.JScrollPane jspRecebimentos;
    private javax.swing.JScrollPane jspUsuario;
    private javax.swing.JScrollPane jspVendas;
    private javax.swing.JLabel lblProdutos;
    private javax.swing.JLabel lblProdutosExibirAlfabetica;
    private javax.swing.JLabel lblProdutosPesquisa;
    private javax.swing.JLabel lblRecebimentos;
    private javax.swing.JLabel lblRecebimentosExibir;
    private javax.swing.JLabel lblRecebimentosPesquisa;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloUsuarios;
    private javax.swing.JLabel lblUsuariosExibir;
    private javax.swing.JLabel lblUsuariosPesquisa;
    private javax.swing.JLabel lblVendas;
    private javax.swing.JLabel lblVendasExibir;
    private javax.swing.JLabel lblVendasPesquisa;
    private javax.swing.JPanel pnlMenuInicial;
    private javax.swing.JPanel pnlProdutos;
    private javax.swing.JPanel pnlProdutosMenu;
    private javax.swing.JPanel pnlRecebimentoMenu;
    private javax.swing.JPanel pnlRecebimentos;
    private javax.swing.JPanel pnlUsuarios;
    private javax.swing.JPanel pnlUsuariosMenu;
    private javax.swing.JPanel pnlVendas;
    private javax.swing.JPanel pnlVendasMenu;
    private javax.swing.JTable tblProdutos;
    private javax.swing.JTable tblRecebimentos;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JTable tblVendas;
    private javax.swing.JTextField txtProdutosPesquisa;
    private javax.swing.JTextField txtRecebimentosPesquisa;
    private javax.swing.JTextField txtUsuariosPesquisa;
    private javax.swing.JTextField txtVendasPesquisa;
    // End of variables declaration//GEN-END:variables

}
